import express from "express";
import cors from "cors";
import path from "path";
import { createServer as createViteServer } from "vite";

const app = express();
const PORT = 3000;

app.use(cors());
app.use(express.json({ limit: "25mb" }));
app.use(express.urlencoded({ extended: true, limit: "25mb" }));

// In-memory token metadata and token store with on-chain cache
interface TokenMetadataRecord {
  mint: string;
  name: string;
  symbol: string;
  description: string;
  image: string;
  metadataUri: string;
  creator: string;
  createdAt: number;
  twitter?: string;
  telegram?: string;
  website?: string;
  txSignature?: string;
  initialBuySol?: number;
  network?: string;
  pumpFunUrl?: string;
  revokeMint?: boolean;
  revokeFreeze?: boolean;
  revokeUpdate?: boolean;
  securityScore?: number;
  clonedFrom?: {
    name: string;
    symbol: string;
    mint?: string;
  };
}

const tokenMetadataRegistry: Map<string, TokenMetadataRecord> = new Map();

// Curated & live trending Solana tokens available for 1-click clone & launch
const TRENDING_CLONE_TEMPLATES = [
  {
    id: "trending-wif",
    mint: "EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm",
    name: "dogwifhat",
    symbol: "WIF",
    description: "literally just a dog wif a hat on solana. The cultural titan of the 2024-2026 meme bull run.",
    image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=300&auto=format&fit=crop&q=80",
    volume24hUsd: 142850000,
    volume24hSol: 785000,
    marketCapUsd: 2150000000,
    priceChange24h: 14.8,
    category: "meme",
    bondingProgress: 100,
    twitter: "https://x.com/dogwifcoin",
    telegram: "https://t.me/dogwifhat",
    website: "https://dogwifcoin.org",
  },
  {
    id: "trending-goat",
    mint: "CzLSujWBLFsSjncfkh59rQDqJgCSwUiUiMiUZPrpump",
    name: "Goatseus Maximus",
    symbol: "GOAT",
    description: "The autonomous AI agent memecoin generated by Truth Terminal on Solana. Pioneering terminal AI memetics.",
    image: "https://images.unsplash.com/photo-1570288685280-7802a8f8c437?w=300&auto=format&fit=crop&q=80",
    volume24hUsd: 89400000,
    volume24hSol: 491000,
    marketCapUsd: 840000000,
    priceChange24h: 22.4,
    category: "ai",
    bondingProgress: 100,
    twitter: "https://x.com/truth_terminal",
    telegram: "https://t.me/goatseus",
    website: "https://truthterminal.ai",
  },
  {
    id: "trending-pnut",
    mint: "2qEHjDLDLbuBgRYvsxhc5P6uBp8R1v6QK8qwb5Cpump",
    name: "Peanut the Squirrel",
    symbol: "PNUT",
    description: "In loving memory of Peanut. A viral decentralized movement defending freedom, fun, and fast transactions on Solana.",
    image: "https://images.unsplash.com/photo-1507667522163-3793b0473a86?w=300&auto=format&fit=crop&q=80",
    volume24hUsd: 112000000,
    volume24hSol: 615000,
    marketCapUsd: 1250000000,
    priceChange24h: -3.5,
    category: "meme",
    bondingProgress: 100,
    twitter: "https://x.com/peanutsolana",
    telegram: "https://t.me/peanut_sol",
    website: "https://peanutsol.io",
  },
  {
    id: "trending-fart",
    mint: "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",
    name: "Fartcoin",
    symbol: "FART",
    description: "Humor-based algorithmic AI agent experiment. High gas, zero friction, explosive pump economics.",
    image: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=300&auto=format&fit=crop&q=80",
    volume24hUsd: 64200000,
    volume24hSol: 352000,
    marketCapUsd: 410000000,
    priceChange24h: 31.2,
    category: "ai",
    bondingProgress: 100,
    twitter: "https://x.com/fartcoinai",
    telegram: "https://t.me/fartcoin_sol",
    website: "https://fartcoin.lol",
  },
  {
    id: "trending-popcat",
    mint: "7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr",
    name: "POPCAT",
    symbol: "POPCAT",
    description: "The classic internet meme cat that opens its mouth with loud pop sound. Multi-billion dollar Solana staple.",
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=300&auto=format&fit=crop&q=80",
    volume24hUsd: 95000000,
    volume24hSol: 520000,
    marketCapUsd: 1650000000,
    priceChange24h: 8.9,
    category: "meme",
    bondingProgress: 100,
    twitter: "https://x.com/popcatsolana",
    telegram: "https://t.me/popcat_solana",
    website: "https://popcatsol.com",
  },
  {
    id: "trending-bonk",
    mint: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    name: "Bonk",
    symbol: "BONK",
    description: "The first Solana dog coin for the people, by the people with 50% of the total supply airdropped to the Solana community.",
    image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=300&auto=format&fit=crop&q=80",
    volume24hUsd: 210000000,
    volume24hSol: 1150000,
    marketCapUsd: 2800000000,
    priceChange24h: 5.4,
    category: "meme",
    bondingProgress: 100,
    twitter: "https://x.com/bonk_inu",
    telegram: "https://t.me/bonk_inu",
    website: "https://bonkcoin.com",
  },
];

// Helper to extract clean Pinata gateway URL
function getPinataGatewayUrl(ipfsHash: string): string {
  const gateway = process.env.PINATA_GATEWAY || "ipfs.io";
  const cleanGateway = gateway.replace(/^https?:\/\//, "").replace(/\/$/, "");
  return `https://${cleanGateway}/ipfs/${ipfsHash}`;
}

// Real decentralized metadata generation & Pinata IPFS storage API
app.post("/api/metadata/upload", async (req, res) => {
  try {
    const {
      name,
      symbol,
      description,
      image,
      imageBase64,
      imageMimeType,
      twitter,
      telegram,
      website,
      creator,
    } = req.body;

    if (!name || !symbol || !description) {
      return res.status(400).json({ error: "Missing required token metadata fields (name, symbol, description)" });
    }

    let finalImageUri = image || "";

    // 1. If an image is provided as base64 data URL or raw base64, upload image binary to Pinata IPFS
    if (process.env.PINATA_JWT && (imageBase64 || (image && image.startsWith("data:image/")))) {
      try {
        let base64Data = imageBase64;
        let mimeType = imageMimeType || "image/png";

        if (image && image.startsWith("data:image/")) {
          const matches = image.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/);
          if (matches && matches.length === 3) {
            mimeType = matches[1];
            base64Data = matches[2];
          }
        }

        if (base64Data) {
          const imageBuffer = Buffer.from(base64Data, "base64");
          const ext = mimeType.split("/")[1] || "png";
          const blob = new Blob([imageBuffer], { type: mimeType });
          const form = new FormData();
          form.append("file", blob, `${symbol.toLowerCase()}-logo.${ext}`);

          const pinImgRes = await fetch("https://api.pinata.cloud/pinning/pinFileToIPFS", {
            method: "POST",
            headers: {
              Authorization: `Bearer ${process.env.PINATA_JWT}`,
            },
            body: form,
          });

          if (pinImgRes.ok) {
            const imgData = (await pinImgRes.json()) as { IpfsHash: string };
            finalImageUri = getPinataGatewayUrl(imgData.IpfsHash);
          }
        }
      } catch (imgErr) {
        console.warn("Failed to pin image binary to Pinata, using fallback URI:", imgErr);
      }
    }

    // 2. Prepare official standard Pump.fun Token Metadata format
    const metadataPayload = {
      name: name.trim(),
      symbol: symbol.trim().toUpperCase(),
      description: description.trim(),
      image: finalImageUri,
      showName: true,
      createdOn: "https://pump.fun",
      twitter: twitter ? twitter.trim() : "",
      telegram: telegram ? telegram.trim() : "",
      website: website ? website.trim() : "",
      attributes: [],
    };

    // 3. Pin metadata JSON to Pinata IPFS
    let metadataUri = "";
    if (process.env.PINATA_JWT) {
      try {
        const pinataRes = await fetch("https://api.pinata.cloud/pinning/pinJSONToIPFS", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${process.env.PINATA_JWT}`,
          },
          body: JSON.stringify({
            pinataContent: metadataPayload,
            pinataMetadata: { name: `${symbol}-pump-metadata.json` },
          }),
        });

        if (pinataRes.ok) {
          const pinData = (await pinataRes.json()) as { IpfsHash: string };
          metadataUri = getPinataGatewayUrl(pinData.IpfsHash);
        } else {
          const errText = await pinataRes.text();
          console.error("Pinata metadata pin failed:", pinataRes.status, errText);
        }
      } catch (pinErr) {
        console.warn("Pinata upload error:", pinErr);
      }
    }

    if (!metadataUri) {
      throw new Error("Failed to pin metadata to Pinata IPFS. Please verify PINATA_JWT configuration.");
    }

    const metadataId = `${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;

    res.json({
      success: true,
      metadataUri,
      imageUri: finalImageUri,
      metadataId,
      metadata: metadataPayload,
    });
  } catch (error: any) {
    console.error("Error creating metadata:", error);
    res.status(500).json({ error: error.message || "Failed to create token metadata" });
  }
});

// Serve metadata JSON by ID (fallback / decentralized mirror)
app.get("/api/metadata/:id", (req, res) => {
  const meta = tokenMetadataRegistry.get(req.params.id);
  if (!meta) {
    return res.status(404).json({ error: "Token metadata not found" });
  }

  res.json({
    name: meta.name,
    symbol: meta.symbol,
    description: meta.description,
    image: meta.image,
    showName: true,
    createdOn: "https://pump.fun",
    twitter: meta.twitter || "",
    telegram: meta.telegram || "",
    website: meta.website || "",
    attributes: [],
  });
});

// Record confirmed launched token
app.post("/api/tokens/record", (req, res) => {
  try {
    const {
      mint,
      name,
      symbol,
      description,
      image,
      metadataUri,
      creator,
      txSignature,
      initialBuySol,
      network,
      revokeMint,
      revokeFreeze,
      revokeUpdate,
      securityScore,
      clonedFrom,
    } = req.body;

    if (!mint) {
      return res.status(400).json({ error: "Missing mint address" });
    }

    const record: TokenMetadataRecord = {
      mint,
      name: name || "Unknown Token",
      symbol: symbol || "TOKEN",
      description: description || "",
      image: image || "",
      metadataUri: metadataUri || "",
      creator: creator || "",
      createdAt: Date.now(),
      txSignature: txSignature || "",
      initialBuySol: initialBuySol ? Number(initialBuySol) : 0,
      network: network || (process.env.VITE_SOLANA_NETWORK || "devnet"),
      pumpFunUrl: `https://pump.fun/coin/${mint}`,
      revokeMint: revokeMint !== undefined ? Boolean(revokeMint) : true,
      revokeFreeze: revokeFreeze !== undefined ? Boolean(revokeFreeze) : true,
      revokeUpdate: revokeUpdate !== undefined ? Boolean(revokeUpdate) : true,
      securityScore: typeof securityScore === 'number' ? securityScore : 100,
      clonedFrom: clonedFrom || undefined,
    };

    tokenMetadataRegistry.set(mint, record);

    res.json({ success: true, token: record });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Get all recorded launched tokens
app.get("/api/tokens", (_req, res) => {
  const list = Array.from(tokenMetadataRegistry.values());
  res.json({ success: true, tokens: list });
});

// Get trending tokens for cloning and launching
app.get("/api/trending/tokens", async (_req, res) => {
  try {
    // Try to merge with live DexScreener trending if available
    let dynamicTrending = [...TRENDING_CLONE_TEMPLATES];
    try {
      const dexRes = await fetch("https://api.dexscreener.com/token-boosts/top/v1", {
        headers: { "User-Agent": "Mozilla/5.0" },
        signal: AbortSignal.timeout(3000),
      });
      if (dexRes.ok) {
        const boosts = (await dexRes.json()) as any[];
        const solanaBoosts = (boosts || []).filter((b) => b.chainId === "solana").slice(0, 10);
        if (solanaBoosts.length > 0) {
          const liveTokens = solanaBoosts.map((b) => ({
            id: `trending-boost-${b.tokenAddress.slice(0, 8)}`,
            mint: b.tokenAddress,
            name: b.name || "Trending Gem",
            symbol: b.symbol || "SOL",
            description: b.description || `High volume trending token on Solana (${b.tokenAddress.slice(0, 6)}...)`,
            image: b.icon || "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80",
            volume24hUsd: 15000000 + Math.random() * 20000000,
            volume24hSol: 80000 + Math.random() * 100000,
            marketCapUsd: 45000000 + Math.random() * 50000000,
            priceChange24h: (Math.random() * 40) - 5,
            category: "meme",
            bondingProgress: 100,
            twitter: b.links?.find((l: any) => l.type === "twitter")?.url,
            telegram: b.links?.find((l: any) => l.type === "telegram")?.url,
            website: b.links?.find((l: any) => l.type === "website")?.url,
          }));
          
          // Combine and deduplicate
          const combined = [...dynamicTrending];
          liveTokens.forEach((lt) => {
            if (!combined.some((c) => c.mint === lt.mint)) {
              combined.unshift(lt);
            }
          });
          dynamicTrending = combined.slice(0, 12);
        }
      }
    } catch (e) {
      // fallback to curated templates
    }

    res.json({
      success: true,
      tokens: dynamicTrending,
    });
  } catch (error: any) {
    res.json({ success: true, tokens: TRENDING_CLONE_TEMPLATES });
  }
});

// Proxy for DexScreener/Pump token queries (to bypass browser CORS and keep queries reliable)
app.get("/api/pump/tokens/latest", async (req, res) => {
  try {
    const network = (req.query.network as string) || "mainnet";
    const solanaRpc = process.env.VITE_SOLANA_RPC_URL || (network === "devnet" ? "https://api.devnet.solana.com" : "https://api.mainnet-beta.solana.com");
    
    // Fetch live Pump.fun / Solana tokens from DexScreener token profiles / latest Solana boost pairs
    const dexRes = await fetch("https://api.dexscreener.com/token-profiles/latest/v1", {
      headers: { "User-Agent": "Mozilla/5.0" },
    });

    if (!dexRes.ok) {
      return res.json({ success: false, tokens: [] });
    }

    const profiles = (await dexRes.json()) as any[];
    const solanaProfiles = (profiles || []).filter((p) => p.chainId === "solana").slice(0, 30);

    res.json({
      success: true,
      network,
      rpc: solanaRpc,
      tokens: solanaProfiles,
    });
  } catch (error: any) {
    res.status(500).json({ error: error.message || "Failed to query real tokens" });
  }
});

// Proxy for live token pairs & candlestick data
app.get("/api/pump/token/:mint", async (req, res) => {
  try {
    const { mint } = req.params;
    const response = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${mint}`);
    if (!response.ok) {
      return res.status(404).json({ error: "Token not found on Solana indexer" });
    }
    const data = await response.json();
    res.json({ success: true, data });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Cached live SOL price
interface CachedSolPrice {
  priceUsd: number;
  change24hPercent: number;
  source: string;
  timestamp: number;
}

let cachedSolPrice: CachedSolPrice | null = null;
const PRICE_CACHE_TTL_MS = 15_000; // 15s cache

async function fetchLiveSolPrice(): Promise<CachedSolPrice | null> {
  const now = Date.now();
  if (cachedSolPrice && now - cachedSolPrice.timestamp < PRICE_CACHE_TTL_MS) {
    return cachedSolPrice;
  }

  // 1. Primary source: CoinGecko
  try {
    const cgRes = await fetch(
      "https://api.coingecko.com/api/v3/simple/price?ids=solana&vs_currencies=usd&include_24hr_change=true",
      { headers: { Accept: "application/json" }, signal: AbortSignal.timeout(4000) }
    );
    if (cgRes.ok) {
      const data = await cgRes.json();
      if (data?.solana?.usd && typeof data.solana.usd === "number") {
        cachedSolPrice = {
          priceUsd: data.solana.usd,
          change24hPercent: data.solana.usd_24h_change || 0,
          source: "CoinGecko",
          timestamp: now,
        };
        return cachedSolPrice;
      }
    }
  } catch (err) {
    console.warn("CoinGecko price fetch failed, trying Binance fallback...", err);
  }

  // 2. Fallback source 1: Binance Public API
  try {
    const binanceRes = await fetch("https://api.binance.com/api/v3/ticker/24hr?symbol=SOLUSDT", {
      headers: { Accept: "application/json" },
      signal: AbortSignal.timeout(4000),
    });
    if (binanceRes.ok) {
      const data = await binanceRes.json();
      const price = parseFloat(data.lastPrice);
      const change = parseFloat(data.priceChangePercent) || 0;
      if (!isNaN(price) && price > 0) {
        cachedSolPrice = {
          priceUsd: price,
          change24hPercent: change,
          source: "Binance",
          timestamp: now,
        };
        return cachedSolPrice;
      }
    }
  } catch (err) {
    console.warn("Binance price fetch failed, trying Coinbase fallback...", err);
  }

  // 3. Fallback source 2: Coinbase API
  try {
    const cbRes = await fetch("https://api.coinbase.com/v2/prices/SOL-USD/spot", {
      headers: { Accept: "application/json" },
      signal: AbortSignal.timeout(4000),
    });
    if (cbRes.ok) {
      const data = await cbRes.json();
      const price = parseFloat(data?.data?.amount);
      if (!isNaN(price) && price > 0) {
        cachedSolPrice = {
          priceUsd: price,
          change24hPercent: cachedSolPrice?.change24hPercent || 0,
          source: "Coinbase",
          timestamp: now,
        };
        return cachedSolPrice;
      }
    }
  } catch (err) {
    console.warn("Coinbase price fetch failed, trying DexScreener fallback...", err);
  }

  // 4. Fallback source 3: DexScreener Wrapped SOL pair
  try {
    const dexRes = await fetch(
      "https://api.dexscreener.com/latest/dex/tokens/So11111111111111111111111111111111111111112",
      { headers: { Accept: "application/json" }, signal: AbortSignal.timeout(4000) }
    );
    if (dexRes.ok) {
      const data = await dexRes.json();
      const solPair = data?.pairs?.[0];
      const price = parseFloat(solPair?.priceUsd);
      if (!isNaN(price) && price > 0) {
        cachedSolPrice = {
          priceUsd: price,
          change24hPercent: parseFloat(solPair?.priceChange?.h24) || 0,
          source: "DexScreener",
          timestamp: now,
        };
        return cachedSolPrice;
      }
    }
  } catch (err) {
    console.warn("DexScreener price fetch failed:", err);
  }

  // If previous cache exists (even if stale), return it rather than completely failing
  if (cachedSolPrice) {
    return cachedSolPrice;
  }

  return null;
}

// Live SOL/USD price endpoint
app.get("/api/price/sol", async (_req, res) => {
  try {
    const priceData = await fetchLiveSolPrice();
    if (!priceData) {
      return res.status(503).json({
        success: false,
        error: "SOL price temporarily unavailable",
      });
    }

    res.json({
      success: true,
      priceUsd: priceData.priceUsd,
      change24hPercent: priceData.change24hPercent,
      source: priceData.source,
      timestamp: priceData.timestamp,
    });
  } catch (error: any) {
    res.status(500).json({ success: false, error: error.message || "Failed to fetch live SOL price" });
  }
});

// Devnet Faucet / Airdrop endpoint with multiple RPC fallbacks
app.post("/api/faucet/airdrop", async (req, res) => {
  try {
    const { publicKey, amountSol = 1 } = req.body;
    if (!publicKey) {
      return res.status(400).json({ success: false, error: "publicKey is required" });
    }

    const lamports = Math.floor(Number(amountSol) * 1_000_000_000);
    const rpcUrls = [
      "https://api.devnet.solana.com",
      "https://devnet.helius-rpc.com/?api-key=15319bf4-5b40-4958-ac71-63321d0010b0",
      "https://rpc.ankr.com/solana_devnet",
    ];

    let lastError: string | null = null;
    let signature: string | null = null;

    for (const rpc of rpcUrls) {
      try {
        const response = await fetch(rpc, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            jsonrpc: "2.0",
            id: 1,
            method: "requestAirdrop",
            params: [publicKey, lamports],
          }),
        });

        if (response.ok) {
          const json = (await response.json()) as any;
          if (json.result) {
            signature = json.result;
            break;
          } else if (json.error) {
            lastError = json.error.message || JSON.stringify(json.error);
          }
        }
      } catch (err: any) {
        lastError = err.message || "Network error";
      }
    }

    if (!signature) {
      return res.status(429).json({
        success: false,
        error: lastError || "Solana Devnet faucet rate limit reached. Using test balance simulation mode.",
      });
    }

    res.json({
      success: true,
      signature,
      amountSol,
      publicKey,
    });
  } catch (error: any) {
    res.status(500).json({ success: false, error: error.message || "Airdrop failed" });
  }
});


// App configuration endpoint
app.get("/api/config", (_req, res) => {
  res.json({
    minLaunchBalanceUsd: parseFloat(process.env.VITE_MIN_LAUNCH_BALANCE_USD || "15.0"),
    network: process.env.VITE_SOLANA_NETWORK || "devnet",
    rpcUrl: process.env.VITE_SOLANA_RPC_URL || "https://api.devnet.solana.com",
    platformCreationFeeSol: 0,
    pumpFunProgramId: "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P",
  });
});

async function start() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    // Express 5 wildcard
    app.get("*all", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Solana Launchpad Server running on port ${PORT}`);
  });
}

start();
