import React, { createContext, useContext, useState, useEffect, useCallback } from "react";
import { Token, Trade, Candle, TradeCategory } from "../types/token";
import { useSolana } from "../solana/solanaContext";
import { SOL_PRICE_USD, calculateTokensForSol } from "../solana/bondingCurve";
import { INITIAL_TOKENS } from "./initialTokens";
import { PublicKey } from "@solana/web3.js";

export interface UserHolding {
  token: Token;
  tokenMint: string;
  tokenBalance: number;
  balance: number;
  avgBuyPriceSol: number;
  currentValSol: number;
  currentValUsd: number;
  totalCostSol: number;
  pnlSol: number;
  pnlPercent: number;
}

export interface TrendingToken {
  id: string;
  mint: string;
  name: string;
  symbol: string;
  description: string;
  image: string;
  volume24hUsd: number;
  volume24hSol: number;
  marketCapUsd: number;
  priceChange24h: number;
  category: string;
  bondingProgress: number;
  twitter?: string;
  telegram?: string;
  website?: string;
}

export const DEFAULT_TRENDING_TOKENS: TrendingToken[] = [
  {
    id: "trending-wif",
    mint: "EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm",
    name: "dogwifhat",
    symbol: "WIF",
    description: "literally just a dog wif a hat on solana. The cultural titan of the 2024-2026 meme bull run.",
    image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=300&auto=format&fit=crop&q=80",
    volume24hUsd: 142850000,
    volume24hSol: 785000,
    marketCapUsd: 2150000000,
    priceChange24h: 14.8,
    category: "meme",
    bondingProgress: 100,
    twitter: "https://x.com/dogwifcoin",
    telegram: "https://t.me/dogwifhat",
    website: "https://dogwifcoin.org",
  },
  {
    id: "trending-goat",
    mint: "CzLSujWBLFsSjncfkh59rQDqJgCSwUiUiMiUZPrpump",
    name: "Goatseus Maximus",
    symbol: "GOAT",
    description: "The autonomous AI agent memecoin generated by Truth Terminal on Solana. Pioneering terminal AI memetics.",
    image: "https://images.unsplash.com/photo-1570288685280-7802a8f8c437?w=300&auto=format&fit=crop&q=80",
    volume24hUsd: 89400000,
    volume24hSol: 491000,
    marketCapUsd: 840000000,
    priceChange24h: 22.4,
    category: "ai",
    bondingProgress: 100,
    twitter: "https://x.com/truth_terminal",
    telegram: "https://t.me/goatseus",
    website: "https://truthterminal.ai",
  },
  {
    id: "trending-pnut",
    mint: "2qEHjDLDLbuBgRYvsxhc5P6uBp8R1v6QK8qwb5Cpump",
    name: "Peanut the Squirrel",
    symbol: "PNUT",
    description: "In loving memory of Peanut. A viral decentralized movement defending freedom, fun, and fast transactions on Solana.",
    image: "https://images.unsplash.com/photo-1507667522163-3793b0473a86?w=300&auto=format&fit=crop&q=80",
    volume24hUsd: 112000000,
    volume24hSol: 615000,
    marketCapUsd: 1250000000,
    priceChange24h: -3.5,
    category: "meme",
    bondingProgress: 100,
    twitter: "https://x.com/peanutsolana",
    telegram: "https://t.me/peanut_sol",
    website: "https://peanutsol.io",
  },
  {
    id: "trending-fart",
    mint: "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",
    name: "Fartcoin",
    symbol: "FART",
    description: "Humor-based algorithmic AI agent experiment. High gas, zero friction, explosive pump economics.",
    image: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=300&auto=format&fit=crop&q=80",
    volume24hUsd: 64200000,
    volume24hSol: 352000,
    marketCapUsd: 410000000,
    priceChange24h: 31.2,
    category: "ai",
    bondingProgress: 100,
    twitter: "https://x.com/fartcoinai",
    telegram: "https://t.me/fartcoin_sol",
    website: "https://fartcoin.lol",
  },
  {
    id: "trending-popcat",
    mint: "7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr",
    name: "POPCAT",
    symbol: "POPCAT",
    description: "The classic internet meme cat that opens its mouth with loud pop sound. Multi-billion dollar Solana staple.",
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=300&auto=format&fit=crop&q=80",
    volume24hUsd: 95000000,
    volume24hSol: 520000,
    marketCapUsd: 1650000000,
    priceChange24h: 8.9,
    category: "meme",
    bondingProgress: 100,
    twitter: "https://x.com/popcatsolana",
    telegram: "https://t.me/popcat_solana",
    website: "https://popcatsol.com",
  },
  {
    id: "trending-bonk",
    mint: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    name: "Bonk",
    symbol: "BONK",
    description: "The first Solana dog coin for the people, by the people with 50% of the total supply airdropped to the Solana community.",
    image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=300&auto=format&fit=crop&q=80",
    volume24hUsd: 210000000,
    volume24hSol: 1150000,
    marketCapUsd: 2800000000,
    priceChange24h: 5.4,
    category: "meme",
    bondingProgress: 100,
    twitter: "https://x.com/bonk_inu",
    telegram: "https://t.me/bonk_inu",
    website: "https://bonkcoin.com",
  },
];

// Helper to generate seed trades for any token
function generateSeedTrades(token: Token, liveSolPrice: number): Trade[] {
  const now = Date.now();
  const seedTrades: Trade[] = [];
  const fakeMakers = [
    '7Vzb...9xKp', '4NmK...8tLw', '9Qrt...2pZa', '3Ghy...1vBn', '6Dfs...5kQm',
    '8Jkl...4wXy', '2Mnb...7cVe', '5Zxc...9rTy', '1Plm...3oIu'
  ];

  // 1. Creator / initial launch buy
  seedTrades.push({
    id: `creator-init-${token.mintAddress}`,
    tokenMint: token.mintAddress,
    type: 'buy',
    solAmount: token.solCollected || 1.5,
    tokenAmount: Math.floor((token.solCollected || 1.5) * 33000000),
    priceSol: token.priceSol,
    priceUsd: token.priceUsd,
    makerAddress: token.creatorAddress || 'CreatorWallet',
    makerShort: `${token.creatorAddress?.slice(0, 4) || '7K3v'}...${token.creatorAddress?.slice(-4) || '9pLw'}`,
    timestamp: token.createdAt || (now - 3600000),
    txSignature: `genesis-buy-${token.mintAddress.slice(0, 8)}`,
    isUserTrade: false,
    tradeCategory: 'sniper',
    walletLabel: 'Creator Launch Buy 🎯',
  });

  // 2. Early snipers / bundles
  const sniperCount = Math.min(6, Math.floor((token.bondingProgress || 10) / 12) + 2);
  for (let i = 0; i < sniperCount; i++) {
    const isSniper = i < 3;
    const solAmt = isSniper ? +(0.8 + (i * 0.45)).toFixed(2) : +(0.15 + (i * 0.12)).toFixed(3);
    const tokenAmt = Math.floor(solAmt / (token.priceSol || 0.00000003));
    const makerShort = fakeMakers[i % fakeMakers.length];
    
    seedTrades.unshift({
      id: `seed-trade-${i}-${token.mintAddress}`,
      tokenMint: token.mintAddress,
      type: i === 4 ? 'sell' : 'buy',
      solAmount: solAmt,
      tokenAmount: tokenAmt,
      priceSol: token.priceSol * (1 + (i * 0.04)),
      priceUsd: token.priceUsd * (1 + (i * 0.04)),
      makerAddress: `${makerShort.replace('...', 'SolWalletAddress')}`,
      makerShort,
      timestamp: now - ((sniperCount - i) * 180000),
      txSignature: `tx-seed-${token.mintAddress.slice(0, 6)}-${i}`,
      tradeCategory: isSniper ? 'sniper' : (solAmt > 1.2 ? 'whale' : 'organic'),
      walletLabel: isSniper ? `Bundle Wallet #${i + 1} 🎯` : (solAmt > 1.2 ? 'Whale Trader 🐋' : 'Community Trader 🌿'),
    });
  }

  return seedTrades;
}

// Load launched tokens from localStorage
function getLocalStoredTokens(): Token[] {
  try {
    const raw = localStorage.getItem("swagpad_launched_tokens");
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) return parsed;
    }
  } catch (e) {
    console.warn("Failed to load local stored tokens:", e);
  }
  return [];
}

// Save launched tokens to localStorage
function saveLocalStoredTokens(token: Token) {
  try {
    const existing = getLocalStoredTokens();
    const filtered = existing.filter((t) => t.mintAddress !== token.mintAddress && t.id !== token.id);
    const updated = [token, ...filtered];
    localStorage.setItem("swagpad_launched_tokens", JSON.stringify(updated.slice(0, 100)));
  } catch (e) {
    console.warn("Failed to persist token locally:", e);
  }
}

interface TokenStoreContextType {
  tokens: Token[];
  trendingTokens: TrendingToken[];
  isLoading: boolean;
  error: string | null;
  solPriceUsd: number;
  trades: Record<string, Trade[]>;
  candles: Record<string, Candle[]>;
  userTradeHistory: Trade[];
  clonedTokenDraft: Partial<Token> | null;
  setClonedTokenDraft: (draft: Partial<Token> | null) => void;
  searchQuery: string;
  setSearchQuery: (query: string) => void;
  selectedCategory: string;
  setSelectedCategory: (category: string) => void;
  sortBy: 'bump_order' | 'creation_time' | 'market_cap' | 'volume';
  setSortBy: (sort: 'bump_order' | 'creation_time' | 'market_cap' | 'volume') => void;
  sortDirection: 'asc' | 'desc';
  setSortDirection: (dir: 'asc' | 'desc') => void;
  getTokenByMint: (mint: string) => Token | undefined;
  getTradesForToken: (mint: string) => Trade[];
  getAllCreatorTrades: (creatorAddress?: string) => Trade[];
  getCandlesForToken: (mint: string, interval?: string) => Candle[];
  getUserHoldings: () => UserHolding[];
  getUserCreatedTokens: () => Token[];
  refreshTokens: () => Promise<void>;
  recordLaunchedToken: (token: Partial<Token>, bundleBuys?: Array<{ address: string; solAmount: number; name: string }>) => Promise<void>;
  searchAndFetchCA: (ca: string) => Promise<Token | null>;
  executeTrade: (params: {
    tokenMint: string;
    type: 'buy' | 'sell';
    solAmount: number;
    tokenAmount: number;
  }) => Promise<{ signature: string }>;
  startLiveTradeSimulation: (mint: string) => void;
}

const TokenStoreContext = createContext<TokenStoreContextType | null>(null);

export const TokenStoreProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { network, publicKey, executePumpBuy, executePumpSell, solPriceUsd: liveSolPrice, connection } = useSolana();
  
  // Initialize with initial tokens + locally stored tokens immediately so Vercel never shows an empty screen
  const [tokens, setTokens] = useState<Token[]>(() => {
    const localTokens = getLocalStoredTokens();
    const map = new Map<string, Token>();
    [...localTokens, ...INITIAL_TOKENS].forEach((t) => {
      if (t.mintAddress) map.set(t.mintAddress, t);
    });
    return Array.from(map.values());
  });

  const [trendingTokens, setTrendingTokens] = useState<TrendingToken[]>(DEFAULT_TRENDING_TOKENS);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [solPriceUsd, setSolPriceUsd] = useState<number>(liveSolPrice || SOL_PRICE_USD || 184.5);
  
  // Initial trades initialized from initial tokens
  const [trades, setTrades] = useState<Record<string, Trade[]>>(() => {
    const initialTradeMap: Record<string, Trade[]> = {};
    INITIAL_TOKENS.forEach((t) => {
      initialTradeMap[t.mintAddress] = generateSeedTrades(t, liveSolPrice || 184.5);
    });
    return initialTradeMap;
  });

  const [candles, setCandles] = useState<Record<string, Candle[]>>({});
  const [clonedTokenDraft, setClonedTokenDraft] = useState<Partial<Token> | null>(null);

  const [userTrades, setUserTrades] = useState<Trade[]>(() => {
    try {
      const saved = localStorage.getItem("user_solana_trades");
      return saved ? JSON.parse(saved) : [];
    } catch {
      return [];
    }
  });

  const [searchQuery, setSearchQuery] = useState<string>("");
  const [selectedCategory, setSelectedCategory] = useState<string>("all");
  const [sortBy, setSortBy] = useState<'bump_order' | 'creation_time' | 'market_cap' | 'volume'>("bump_order");
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>("desc");

  // Keep solPriceUsd updated with live context
  useEffect(() => {
    if (liveSolPrice && liveSolPrice > 0) {
      setSolPriceUsd(liveSolPrice);
    }
  }, [liveSolPrice]);

  // Fetch trending tokens from server or DexScreener fallback
  const fetchTrendingTokens = useCallback(async () => {
    try {
      // 1. Try server endpoint first
      let loadedFromServer = false;
      try {
        const res = await fetch("/api/trending/tokens", { signal: AbortSignal.timeout(3500) });
        if (res.ok && res.headers.get("content-type")?.includes("json")) {
          const data = await res.json();
          if (data.tokens && Array.isArray(data.tokens) && data.tokens.length > 0) {
            setTrendingTokens(data.tokens);
            loadedFromServer = true;
          }
        }
      } catch (serverErr) {
        // server endpoint not available on static hosting (e.g. Vercel)
      }

      if (loadedFromServer) return;

      // 2. Direct client-side DexScreener trending boosts fallback
      try {
        const dexRes = await fetch("https://api.dexscreener.com/token-boosts/top/v1", {
          signal: AbortSignal.timeout(4000),
        });
        if (dexRes.ok) {
          const boosts = (await dexRes.json()) as any[];
          const solanaBoosts = (boosts || []).filter((b) => b.chainId === "solana").slice(0, 10);
          if (solanaBoosts.length > 0) {
            const liveTrending = solanaBoosts.map((b) => ({
              id: `boost-${b.tokenAddress.slice(0, 8)}`,
              mint: b.tokenAddress,
              name: b.name || "Trending Gem",
              symbol: b.symbol || "SOL",
              description: b.description || `High volume trending token on Solana (${b.tokenAddress.slice(0, 6)}...)`,
              image: b.icon || "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80",
              volume24hUsd: 18500000 + Math.random() * 25000000,
              volume24hSol: 95000 + Math.random() * 120000,
              marketCapUsd: 55000000 + Math.random() * 60000000,
              priceChange24h: (Math.random() * 45) - 5,
              category: "meme",
              bondingProgress: 100,
              twitter: b.links?.find((l: any) => l.type === "twitter")?.url,
              telegram: b.links?.find((l: any) => l.type === "telegram")?.url,
              website: b.links?.find((l: any) => l.type === "website")?.url,
            }));

            const combined = [...liveTrending, ...DEFAULT_TRENDING_TOKENS];
            const deduped: TrendingToken[] = [];
            const seen = new Set<string>();
            combined.forEach((item) => {
              if (!seen.has(item.mint)) {
                seen.add(item.mint);
                deduped.push(item);
              }
            });
            setTrendingTokens(deduped.slice(0, 12));
            return;
          }
        }
      } catch (dexErr) {
        // fallback to default curated templates
      }

      setTrendingTokens(DEFAULT_TRENDING_TOKENS);
    } catch (e) {
      console.warn("Could not load trending tokens:", e);
      setTrendingTokens(DEFAULT_TRENDING_TOKENS);
    }
  }, []);

  // Fetch real on-chain & indexed tokens with full static Vercel resilience
  const refreshTokens = useCallback(async () => {
    try {
      setError(null);

      // Load locally stored user-launched tokens
      const localStored = getLocalStoredTokens();

      let serverLaunchedTokens: Token[] = [];
      try {
        const localRes = await fetch("/api/tokens", { signal: AbortSignal.timeout(3000) });
        if (localRes.ok && localRes.headers.get("content-type")?.includes("json")) {
          const localData = await localRes.json();
          if (localData.tokens && Array.isArray(localData.tokens)) {
            serverLaunchedTokens = localData.tokens.map((t: any) => ({
              id: t.mint || `token-${t.createdAt}`,
              mintAddress: t.mint || "",
              name: t.name,
              symbol: t.symbol,
              description: t.description,
              logoUrl: t.image || "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80",
              creatorAddress: t.creator,
              creatorName: t.creator ? `${t.creator.slice(0, 4)}...${t.creator.slice(-4)}` : undefined,
              createdAt: t.createdAt,
              priceUsd: 0.0000045,
              priceSol: 0.000000028,
              marketCapSol: 30.0 + (t.initialBuySol || 0),
              marketCapUsd: (30.0 + (t.initialBuySol || 0)) * (liveSolPrice || 184),
              bondingProgress: Math.min(100, 1.5 + ((t.initialBuySol || 0) / 85) * 100),
              volume24hSol: t.initialBuySol || 0.1,
              volume24hUsd: (t.initialBuySol || 0.1) * (liveSolPrice || 184),
              priceChange24h: 3.5,
              liquiditySol: 30.0 + (t.initialBuySol || 0),
              holdersCount: t.initialBuySol ? 2 : 1,
              totalSupply: 1_000_000_000,
              solCollected: t.initialBuySol || 0.1,
              solTarget: 85,
              isBonded: false,
              isCreatedByUser: true,
              revokeMint: t.revokeMint !== undefined ? t.revokeMint : true,
              revokeFreeze: t.revokeFreeze !== undefined ? t.revokeFreeze : true,
              revokeUpdate: t.revokeUpdate !== undefined ? t.revokeUpdate : true,
              securityScore: t.securityScore || 100,
              clonedFrom: t.clonedFrom,
              socials: {
                twitter: t.twitter,
                telegram: t.telegram,
                website: t.website,
              },
            }));
          }
        }
      } catch (e) {
        // Express backend is not running (e.g. Vercel static frontend) -> rely on localStored + INITIAL_TOKENS
      }

      // Fetch live DexScreener latest profiles directly from browser
      let dexLiveTokens: Token[] = [];
      try {
        const dexRes = await fetch("https://api.dexscreener.com/token-profiles/latest/v1", {
          signal: AbortSignal.timeout(4000),
        });
        if (dexRes.ok) {
          const profiles = (await dexRes.json()) as any[];
          const solanaProfiles = (profiles || []).filter((p) => p.chainId === "solana").slice(0, 15);
          dexLiveTokens = solanaProfiles.map((p) => ({
            id: p.tokenAddress,
            mintAddress: p.tokenAddress,
            name: p.name || p.tokenAddress.slice(0, 6),
            symbol: p.symbol || "SOL",
            description: p.description || `Solana on-chain token (${p.tokenAddress.slice(0, 8)}...)`,
            logoUrl: p.icon || "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80",
            creatorAddress: p.tokenAddress.slice(0, 12),
            creatorName: `${p.tokenAddress.slice(0, 4)}...${p.tokenAddress.slice(-4)}`,
            createdAt: Date.now() - 3600000 * 2,
            priceUsd: 0.000032,
            priceSol: 0.00000018,
            marketCapSol: 45.0,
            marketCapUsd: 8200,
            bondingProgress: 18.5,
            volume24hSol: 12.4,
            volume24hUsd: 2280,
            priceChange24h: 4.2,
            liquiditySol: 45.0,
            holdersCount: 42,
            totalSupply: 1_000_000_000,
            solCollected: 15.2,
            solTarget: 85,
            isBonded: false,
            revokeMint: true,
            revokeFreeze: true,
            revokeUpdate: true,
            securityScore: 98,
            socials: {
              website: p.links?.find((l: any) => l.type === "website")?.url,
              twitter: p.links?.find((l: any) => l.type === "twitter")?.url,
              telegram: p.links?.find((l: any) => l.type === "telegram")?.url,
            },
          }));
        }
      } catch (dexErr) {
        // direct DexScreener fetch failed or offline
      }

      // Combine unique tokens by mint address:
      // Priority: 1. Server/Local user launched -> 2. Dex Live Tokens -> 3. INITIAL_TOKENS
      const mintMap = new Map<string, Token>();
      [...INITIAL_TOKENS, ...dexLiveTokens, ...serverLaunchedTokens, ...localStored].forEach((tok) => {
        if (tok.mintAddress) {
          mintMap.set(tok.mintAddress, tok);
        }
      });

      const finalTokens = Array.from(mintMap.values());
      setTokens(finalTokens);

      // Seed trades for any tokens missing trade history
      setTrades((prevTrades) => {
        const nextTrades = { ...prevTrades };
        finalTokens.forEach((tok) => {
          if (!nextTrades[tok.mintAddress] || nextTrades[tok.mintAddress].length === 0) {
            nextTrades[tok.mintAddress] = generateSeedTrades(tok, liveSolPrice || 184.5);
          }
        });
        return nextTrades;
      });

    } catch (err: any) {
      console.warn("Token refresh notice:", err);
    }
  }, [liveSolPrice]);

  useEffect(() => {
    refreshTokens();
    fetchTrendingTokens();
    const timer = setInterval(() => {
      refreshTokens();
    }, 15000);
    return () => clearInterval(timer);
  }, [refreshTokens, fetchTrendingTokens]);

  const getTokenByMint = useCallback(
    (mint: string) => {
      return tokens.find((t) => t.mintAddress.toLowerCase() === mint.toLowerCase() || t.id.toLowerCase() === mint.toLowerCase());
    },
    [tokens]
  );

  const getTradesForToken = useCallback(
    (mint: string): Trade[] => {
      if (trades[mint] && trades[mint].length > 0) {
        return trades[mint];
      }
      const tok = getTokenByMint(mint);
      if (tok) {
        const generated = generateSeedTrades(tok, liveSolPrice || 184.5);
        return generated;
      }
      return [];
    },
    [trades, getTokenByMint, liveSolPrice]
  );

  // Return all buys and sells across all tokens launched by creator
  const getAllCreatorTrades = useCallback(
    (creatorAddress?: string): Trade[] => {
      const targetCreator = (creatorAddress || publicKey || "").toLowerCase();
      if (!targetCreator) return [];

      const creatorMints = new Set(
        tokens
          .filter((t) => t.creatorAddress?.toLowerCase() === targetCreator)
          .map((t) => t.mintAddress)
      );

      const allTrades: Trade[] = [];
      Object.entries(trades).forEach(([mint, mintTrades]) => {
        if (creatorMints.has(mint)) {
          allTrades.push(...mintTrades);
        }
      });

      return allTrades.sort((a, b) => b.timestamp - a.timestamp);
    },
    [publicKey, tokens, trades]
  );

  const getCandlesForToken = useCallback(
    (mint: string, interval?: string): Candle[] => {
      if (candles[mint] && candles[mint].length > 0) {
        return candles[mint];
      }
      const tok = getTokenByMint(mint);
      const basePrice = tok?.priceUsd || 0.0000045;
      const now = Math.floor(Date.now() / 1000);
      return [
        {
          timestamp: now - 3600,
          open: basePrice * 0.95,
          high: basePrice * 1.05,
          low: basePrice * 0.92,
          close: basePrice * 1.02,
          volumeSol: 1.2,
        },
        {
          timestamp: now,
          open: basePrice * 1.02,
          high: basePrice * 1.12,
          low: basePrice * 1.01,
          close: basePrice * 1.08,
          volumeSol: 2.8,
        },
      ];
    },
    [candles, getTokenByMint]
  );

  // Background Live Trade Stream for active & newly launched tokens
  const startLiveTradeSimulation = useCallback((mint: string) => {
    const interval = setInterval(() => {
      setTrades((prev) => {
        const currentList = prev[mint] || [];
        if (currentList.length > 80) return prev;

        const isBuy = Math.random() > 0.35; // 65% buys
        const solAmt = isBuy
          ? (Math.random() < 0.15 ? +(1.2 + Math.random() * 2.5).toFixed(2) : +(0.05 + Math.random() * 0.45).toFixed(3))
          : +(0.03 + Math.random() * 0.25).toFixed(3);

        const tokenCalculation = calculateTokensForSol(solAmt, 30);
        const tokenAmt = Math.floor(tokenCalculation.tokensOut || (solAmt / 0.00000003));
        const priceSol = solAmt / (tokenAmt || 1);
        const priceUsd = priceSol * (liveSolPrice || 184);

        let tradeCategory: TradeCategory = 'organic';
        let walletLabel = 'Community Trader 🌿';
        if (solAmt >= 1.5) {
          tradeCategory = 'whale';
          walletLabel = 'Whale Trader 🐋';
        } else if (Math.random() < 0.25) {
          tradeCategory = 'bot';
          walletLabel = 'MEV / Fast Bot ⚡';
        }

        const fakeMakers = [
          '7Vzb...9xKp', '4NmK...8tLw', '9Qrt...2pZa', '3Ghy...1vBn', '6Dfs...5kQm',
          '8Jkl...4wXy', '2Mnb...7cVe', '5Zxc...9rTy', '1Plm...3oIu'
        ];
        const makerShort = fakeMakers[Math.floor(Math.random() * fakeMakers.length)];
        const makerAddress = `${makerShort.replace('...', 'SolanaTxLive')}`;
        const txSig = `live-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`;

        const newTrade: Trade = {
          id: txSig,
          tokenMint: mint,
          type: isBuy ? 'buy' : 'sell',
          solAmount: solAmt,
          tokenAmount: tokenAmt,
          priceSol,
          priceUsd,
          makerAddress,
          makerShort,
          timestamp: Date.now(),
          txSignature: txSig,
          tradeCategory,
          walletLabel,
        };

        return {
          ...prev,
          [mint]: [newTrade, ...currentList],
        };
      });
    }, 4000 + Math.random() * 3000);

    setTimeout(() => clearInterval(interval), 600000);
  }, [liveSolPrice]);

  // Real-time On-Chain & DexScreener Contract Address (CA) Resolver
  const searchAndFetchCA = useCallback(
    async (ca: string): Promise<Token | null> => {
      const cleanCA = ca.trim();
      if (!cleanCA) return null;

      // 1. Check if token already exists in current memory
      const existing = tokens.find(
        (t) => t.mintAddress.toLowerCase() === cleanCA.toLowerCase() || t.id.toLowerCase() === cleanCA.toLowerCase()
      );
      if (existing) return existing;

      // 2. Validate Solana Base58 format
      let isSolanaPubkey = false;
      try {
        new PublicKey(cleanCA);
        isSolanaPubkey = true;
      } catch {
        // Not a pure base58 32-byte pubkey
      }

      if (!isSolanaPubkey && cleanCA.length < 30) {
        return null;
      }

      // 3. Query DexScreener Free Public API
      try {
        const dexRes = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${cleanCA}`, {
          signal: AbortSignal.timeout(5000),
        });

        if (dexRes.ok) {
          const dexData = await dexRes.json();
          const pairs = dexData?.pairs;
          if (Array.isArray(pairs) && pairs.length > 0) {
            // Sort by highest liquidity or highest volume
            const bestPair = pairs.sort(
              (a: any, b: any) => (b.liquidity?.usd || 0) - (a.liquidity?.usd || 0)
            )[0];

            const baseToken = bestPair.baseToken;
            const priceUsdNum = parseFloat(bestPair.priceUsd) || 0.00003;
            const priceSolNum = parseFloat(bestPair.priceNative) || (priceUsdNum / (liveSolPrice || 184));
            const marketCapUsdNum = bestPair.fdv || bestPair.marketCap || (priceUsdNum * 1_000_000_000);
            const marketCapSolNum = marketCapUsdNum / (liveSolPrice || 184);
            const volume24hSolNum = (bestPair.volume?.h24 || 1000) / (liveSolPrice || 184);
            const priceChange24hNum = parseFloat(bestPair.priceChange?.h24) || 0;
            const liquiditySolNum = (bestPair.liquidity?.usd || 5000) / (liveSolPrice || 184);

            const fetchedToken: Token = {
              id: cleanCA,
              mintAddress: cleanCA,
              name: baseToken.name || "Solana Token",
              symbol: baseToken.symbol || "SOL",
              description: `Verified Solana On-Chain SPL Token (${cleanCA.slice(0, 6)}...${cleanCA.slice(-4)}). Active trading pool on ${bestPair.dexId || "Raydium/Pump"}.`,
              logoUrl:
                bestPair.info?.imageUrl ||
                bestPair.info?.header ||
                `https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80`,
              creatorAddress: bestPair.pairAddress || cleanCA.slice(0, 16),
              creatorName: `${cleanCA.slice(0, 4)}...${cleanCA.slice(-4)}`,
              createdAt: Date.now() - 3600000 * 24,
              priceUsd: priceUsdNum,
              priceSol: priceSolNum,
              marketCapSol: marketCapSolNum,
              marketCapUsd: marketCapUsdNum,
              bondingProgress: 100,
              volume24hSol: volume24hSolNum,
              volume24hUsd: bestPair.volume?.h24 || (volume24hSolNum * (liveSolPrice || 184)),
              priceChange24h: priceChange24hNum,
              liquiditySol: liquiditySolNum,
              holdersCount: bestPair.txns?.h24 ? Math.max(25, Math.floor((bestPair.txns.h24.buys || 10) * 1.5)) : 50,
              totalSupply: 1_000_000_000,
              solCollected: 85,
              solTarget: 85,
              isBonded: true,
              raydiumPoolAddress: bestPair.pairAddress,
              revokeMint: true,
              revokeFreeze: true,
              revokeUpdate: true,
              securityScore: 95,
              socials: {
                website: bestPair.info?.websites?.[0]?.url,
                twitter: bestPair.info?.socials?.find((s: any) => s.type === "twitter")?.url,
                telegram: bestPair.info?.socials?.find((s: any) => s.type === "telegram")?.url,
              },
            };

            // Save to memory and local storage
            setTokens((prev) => {
              const without = prev.filter((t) => t.mintAddress !== cleanCA);
              return [fetchedToken, ...without];
            });

            saveLocalStoredTokens(fetchedToken);

            // Generate trade history and start live simulator
            setTrades((prev) => ({
              ...prev,
              [cleanCA]: generateSeedTrades(fetchedToken, liveSolPrice || 184.5),
            }));
            startLiveTradeSimulation(cleanCA);

            return fetchedToken;
          }
        }
      } catch (dexErr) {
        console.warn("DexScreener CA fetch notice:", dexErr);
      }

      // 4. Fallback: Query Solana RPC directly to verify mint address exists on-chain
      if (isSolanaPubkey) {
        try {
          const pubkey = new PublicKey(cleanCA);
          const accountInfo = await connection.getAccountInfo(pubkey);
          if (accountInfo) {
            // Valid on-chain account / mint on Solana
            const fallbackToken: Token = {
              id: cleanCA,
              mintAddress: cleanCA,
              name: `Solana Mint (${cleanCA.slice(0, 4)}...${cleanCA.slice(-4)})`,
              symbol: cleanCA.slice(0, 4).toUpperCase(),
              description: `On-chain Solana account ${cleanCA} detected directly via RPC. Ready for custom launchpad swap or 1-Click clone!`,
              logoUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80",
              creatorAddress: cleanCA.slice(0, 16),
              createdAt: Date.now() - 3600000,
              priceUsd: 0.000005,
              priceSol: 0.00000003,
              marketCapSol: 30.0,
              marketCapUsd: 30.0 * (liveSolPrice || 184),
              bondingProgress: 1.5,
              volume24hSol: 0.5,
              volume24hUsd: 0.5 * (liveSolPrice || 184),
              priceChange24h: 0,
              liquiditySol: 30.0,
              holdersCount: 1,
              totalSupply: 1_000_000_000,
              solCollected: 0.5,
              solTarget: 85,
              isBonded: false,
              revokeMint: true,
              revokeFreeze: true,
              revokeUpdate: true,
              securityScore: 90,
              socials: {},
            };

            setTokens((prev) => {
              const without = prev.filter((t) => t.mintAddress !== cleanCA);
              return [fallbackToken, ...without];
            });
            saveLocalStoredTokens(fallbackToken);
            return fallbackToken;
          }
        } catch (rpcErr) {
          console.warn("RPC CA verification notice:", rpcErr);
        }
      }

      return null;
    },
    [tokens, liveSolPrice, connection, startLiveTradeSimulation]
  );

  const recordLaunchedToken = async (
    tokenData: Partial<Token>,
    bundleBuys?: Array<{ address: string; solAmount: number; name: string }>
  ) => {
    const mint = tokenData.mintAddress || tokenData.id || `token-${Date.now()}`;
    const now = Date.now();

    const fullToken: Token = {
      id: mint,
      mintAddress: mint,
      name: tokenData.name || "Swagpad Token",
      symbol: tokenData.symbol || "SWAG",
      description: tokenData.description || "",
      logoUrl: tokenData.logoUrl || "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80",
      creatorAddress: tokenData.creatorAddress || publicKey || "Creator",
      creatorName: tokenData.creatorAddress ? `${tokenData.creatorAddress.slice(0, 4)}...${tokenData.creatorAddress.slice(-4)}` : undefined,
      createdAt: now,
      priceUsd: 0.0000045,
      priceSol: 0.000000028,
      marketCapSol: 30.0 + (tokenData.volume24hSol || 0),
      marketCapUsd: (30.0 + (tokenData.volume24hSol || 0)) * (liveSolPrice || 184),
      bondingProgress: Math.min(100, 1.5 + ((tokenData.volume24hSol || 0) / 85) * 100),
      volume24hSol: tokenData.volume24hSol || 0.1,
      volume24hUsd: (tokenData.volume24hSol || 0.1) * (liveSolPrice || 184),
      priceChange24h: 3.5,
      liquiditySol: 30.0 + (tokenData.volume24hSol || 0),
      holdersCount: (bundleBuys?.length || 0) + 1,
      totalSupply: 1_000_000_000,
      solCollected: tokenData.volume24hSol || 0.1,
      solTarget: 85,
      isBonded: false,
      isCreatedByUser: true,
      revokeMint: tokenData.revokeMint !== undefined ? tokenData.revokeMint : true,
      revokeFreeze: tokenData.revokeFreeze !== undefined ? tokenData.revokeFreeze : true,
      revokeUpdate: tokenData.revokeUpdate !== undefined ? tokenData.revokeUpdate : true,
      securityScore: tokenData.securityScore || 100,
      clonedFrom: tokenData.clonedFrom,
      socials: tokenData.socials,
    };

    // 1. Immediately persist to localStorage for Vercel/static reliability
    saveLocalStoredTokens(fullToken);

    // 2. Add to active tokens state
    setTokens((prev) => {
      const without = prev.filter((t) => t.mintAddress !== mint);
      return [fullToken, ...without];
    });

    // 3. Try server endpoint if available
    try {
      await fetch("/api/tokens/record", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          mint,
          name: tokenData.name,
          symbol: tokenData.symbol,
          description: tokenData.description,
          image: tokenData.logoUrl,
          creator: tokenData.creatorAddress || publicKey,
          twitter: tokenData.socials?.twitter,
          telegram: tokenData.socials?.telegram,
          website: tokenData.socials?.website,
          revokeMint: tokenData.revokeMint !== undefined ? tokenData.revokeMint : true,
          revokeFreeze: tokenData.revokeFreeze !== undefined ? tokenData.revokeFreeze : true,
          revokeUpdate: tokenData.revokeUpdate !== undefined ? tokenData.revokeUpdate : true,
          securityScore: tokenData.securityScore || 100,
          clonedFrom: tokenData.clonedFrom,
        }),
      });
    } catch (e) {
      console.warn("Server token recording notice:", e);
    }

    // 4. Seed initial trade events for launch (Creator buy + sub-wallet snipers)
    const initialTrades: Trade[] = [];

    if (tokenData.volume24hSol && tokenData.volume24hSol > 0) {
      const creatorSol = tokenData.volume24hSol;
      const tokensOut = calculateTokensForSol(creatorSol, 30).tokensOut;
      initialTrades.push({
        id: `creator-buy-${now}`,
        tokenMint: mint,
        type: 'buy',
        solAmount: creatorSol,
        tokenAmount: tokensOut || Math.floor(creatorSol * 33000000),
        priceSol: creatorSol / (tokensOut || 1),
        priceUsd: (creatorSol / (tokensOut || 1)) * (liveSolPrice || 184),
        makerAddress: tokenData.creatorAddress || publicKey || 'Creator',
        makerShort: `${(tokenData.creatorAddress || publicKey || 'You').slice(0, 4)}...${(tokenData.creatorAddress || publicKey || '').slice(-4)}`,
        timestamp: now - 3000,
        txSignature: `launch-tx-${now}`,
        isUserTrade: true,
        tradeCategory: 'sniper',
        walletLabel: 'Creator Launch Buy 🎯',
      });
    }

    if (bundleBuys && bundleBuys.length > 0) {
      bundleBuys.forEach((b, idx) => {
        if (b.solAmount > 0) {
          const tokensOut = calculateTokensForSol(b.solAmount, 30.5 + idx * 0.1).tokensOut;
          initialTrades.push({
            id: `bundle-snipe-${idx}-${now}`,
            tokenMint: mint,
            type: 'buy',
            solAmount: b.solAmount,
            tokenAmount: tokensOut || Math.floor(b.solAmount * 32000000),
            priceSol: b.solAmount / (tokensOut || 1),
            priceUsd: (b.solAmount / (tokensOut || 1)) * (liveSolPrice || 184),
            makerAddress: b.address,
            makerShort: `${b.address.slice(0, 4)}...${b.address.slice(-4)}`,
            timestamp: now - (idx * 500),
            txSignature: `bundle-sig-${idx}-${now}`,
            isUserTrade: true,
            tradeCategory: 'sniper',
            walletLabel: `Bundle ${b.name} 🎯`,
          });
        }
      });
    }

    if (initialTrades.length > 0) {
      setTrades((prev) => ({
        ...prev,
        [mint]: initialTrades,
      }));
    }

    startLiveTradeSimulation(mint);
  };

  const executeTrade = async (params: {
    tokenMint: string;
    type: 'buy' | 'sell';
    solAmount: number;
    tokenAmount: number;
  }): Promise<{ signature: string }> => {
    if (!publicKey) throw new Error("Wallet not connected");

    let signature = "";
    if (params.type === "buy") {
      const maxLamports = BigInt(Math.floor(params.solAmount * 1.05 * 1e9));
      const tokenAtoms = BigInt(Math.floor(params.tokenAmount * 1e6));
      signature = await executePumpBuy({
        mint: params.tokenMint,
        tokenAmount: tokenAtoms,
        maxSolCostLamports: maxLamports,
      });
    } else {
      const minLamports = BigInt(Math.floor(params.solAmount * 0.95 * 1e9));
      const tokenAtoms = BigInt(Math.floor(params.tokenAmount * 1e6));
      signature = await executePumpSell({
        mint: params.tokenMint,
        tokenAmount: tokenAtoms,
        minSolOutputLamports: minLamports,
      });
    }

    const makerShort = `${publicKey.slice(0, 4)}...${publicKey.slice(-4)}`;

    const newTrade: Trade = {
      id: signature,
      tokenMint: params.tokenMint,
      type: params.type,
      solAmount: params.solAmount,
      tokenAmount: params.tokenAmount,
      priceSol: params.solAmount / (params.tokenAmount || 1),
      priceUsd: (params.solAmount / (params.tokenAmount || 1)) * (liveSolPrice || 184),
      makerAddress: publicKey,
      makerShort,
      timestamp: Date.now(),
      txSignature: signature,
      isUserTrade: true,
      tradeCategory: 'organic',
      walletLabel: 'You (Trader)',
    };

    setTrades((prev) => ({
      ...prev,
      [params.tokenMint]: [newTrade, ...(prev[params.tokenMint] || [])],
    }));

    setUserTrades((prev) => {
      const updated = [newTrade, ...prev];
      try {
        localStorage.setItem("user_solana_trades", JSON.stringify(updated.slice(0, 100)));
      } catch {}
      return updated;
    });

    return { signature };
  };

  const getUserHoldings = useCallback((): UserHolding[] => {
    if (!publicKey) return [];

    const map = new Map<string, { balance: number; totalCostSol: number }>();
    userTrades.forEach((tr) => {
      const current = map.get(tr.tokenMint) || { balance: 0, totalCostSol: 0 };
      if (tr.type === 'buy') {
        current.balance += tr.tokenAmount;
        current.totalCostSol += tr.solAmount;
      } else {
        current.balance = Math.max(0, current.balance - tr.tokenAmount);
        current.totalCostSol = Math.max(0, current.totalCostSol - tr.solAmount);
      }
      map.set(tr.tokenMint, current);
    });

    const holdings: UserHolding[] = [];
    map.forEach((val, mint) => {
      if (val.balance > 0) {
        const token = getTokenByMint(mint);
        if (token) {
          const currentValSol = val.balance * token.priceSol;
          const currentValUsd = currentValSol * solPriceUsd;
          const pnlSol = currentValSol - val.totalCostSol;
          const pnlPercent = val.totalCostSol > 0 ? (pnlSol / val.totalCostSol) * 100 : 0;
          holdings.push({
            token,
            tokenMint: mint,
            tokenBalance: val.balance,
            balance: val.balance,
            avgBuyPriceSol: val.totalCostSol / (val.balance || 1),
            currentValSol,
            currentValUsd,
            totalCostSol: val.totalCostSol,
            pnlSol,
            pnlPercent,
          });
        }
      }
    });

    return holdings;
  }, [publicKey, userTrades, getTokenByMint, solPriceUsd]);

  const getUserCreatedTokens = useCallback((): Token[] => {
    if (!publicKey) return [];
    return tokens.filter(
      (t) => t.creatorAddress?.toLowerCase() === publicKey.toLowerCase()
    );
  }, [publicKey, tokens]);

  return (
    <TokenStoreContext.Provider
      value={{
        tokens,
        trendingTokens,
        isLoading,
        error,
        solPriceUsd,
        trades,
        candles,
        userTradeHistory: userTrades,
        clonedTokenDraft,
        setClonedTokenDraft,
        searchQuery,
        setSearchQuery,
        selectedCategory,
        setSelectedCategory,
        sortBy,
        setSortBy,
        sortDirection,
        setSortDirection,
        getTokenByMint,
        getTradesForToken,
        getAllCreatorTrades,
        getCandlesForToken,
        getUserHoldings,
        getUserCreatedTokens,
        refreshTokens,
        recordLaunchedToken,
        searchAndFetchCA,
        executeTrade,
        startLiveTradeSimulation,
      }}
    >
      {children}
    </TokenStoreContext.Provider>
  );
};

export const useTokenStore = () => {
  const context = useContext(TokenStoreContext);
  if (!context) {
    throw new Error("useTokenStore must be used within a TokenStoreProvider");
  }
  return context;
};

